version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: notification-postgres
    environment:
      POSTGRES_DB: notificationdb
      POSTGRES_USER: email
      POSTGRES_PASSWORD: email
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: notification-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: notification-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  mailhog:
    image: mailhog/mailhog:latest
    container_name: notification-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: vidajob2882@gmial.com
      PGADMIN_DEFAULT_PASSWORD: 123321
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

  notification-service:
    image: shirinjam/notification-service:main
    container_name: notification-service
    depends_on:
      - postgres
      - kafka
      - mailhog
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: staging
      DB_URL: jdbc:postgresql://postgres:5432/notificationdb
      DB_USERNAME: email
      DB_PASSWORD: email
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USERNAME: ""
      SMTP_API_KEY: ""
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_GROUP_ID: notification-service
      KAFKA_TOPIC: order-confirmed.v1
      APP_INDEX_MAXATTEMPTS: 5

volumes:
  postgres_data:

#//docker compose -f docker-compose.staging.yml up -d

