# with docker-compose.dev.yaml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/emaildb
    username: email
    password: email

  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

app:
  kafka:
    bootstrap-servers: localhost:9092
    group-id: notification-service
    topic: order-confirmed.v1

