spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  mail:
    host:  ${SMTP_HOST} #   smtp.sendgrid.net
    port:  ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:apikey}
    password: ${SMTP_API_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    group-id: ${KAFKA_GROUP_ID:notification-service}
    topic: ${KAFKA_TOPIC:order-confirmed.v1}